### ISSUE TITLE
Error: Could not find or load main class BattleShipsServerApplication

### ISSUE THREAD

**Issue by KenwoodFox** [stan1000/Battleships#1]
```
C:\~>BattleShipsServerApplication.bat
C:\~>java BattleShipsServerApplication
Error: Could not find or load main class BattleShipsServerApplication
```
Any help?

**Comment by stan1000** [comment]
Well, dunno about the setup of your system, any chance there's a problem with it? I also had a (different) issue trying to run the server (it's been a while) and after installing the latest Java SE RE it's worked:
https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

![image](https://user-images.githubusercontent.com/10242414/52562336-7f2b5480-2dfe-11e9-8247-57a0b4b434a2.png)

**Comment by stan1000** [comment]
Classpath was not set properly. This should do the trick:
java -cp BattleShips.jar BattleShipsApplication

**Comment by KenwoodFox** [comment]
Ill give it a go
